// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/ontology/v1/type.pub.proto
// Protobuf C++ Version: 5.29.0

#include "anduril/ontology/v1/type.pub.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace anduril {
namespace ontology {
namespace v1 {
}  // namespace v1
}  // namespace ontology
}  // namespace anduril
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto = nullptr;
const ::uint32_t TableStruct_anduril_2fontology_2fv1_2ftype_2epub_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_anduril_2fontology_2fv1_2ftype_2epub_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\"anduril/ontology/v1/type.pub.proto\022\023an"
    "duril.ontology.v1*\311\001\n\013Disposition\022\027\n\023DIS"
    "POSITION_UNKNOWN\020\000\022\030\n\024DISPOSITION_FRIEND"
    "LY\020\001\022\027\n\023DISPOSITION_HOSTILE\020\002\022\032\n\026DISPOSI"
    "TION_SUSPICIOUS\020\003\022 \n\034DISPOSITION_ASSUMED"
    "_FRIENDLY\020\004\022\027\n\023DISPOSITION_NEUTRAL\020\005\022\027\n\023"
    "DISPOSITION_PENDING\020\006*\236\001\n\013Environment\022\027\n"
    "\023ENVIRONMENT_UNKNOWN\020\000\022\023\n\017ENVIRONMENT_AI"
    "R\020\001\022\027\n\023ENVIRONMENT_SURFACE\020\002\022\033\n\027ENVIRONM"
    "ENT_SUB_SURFACE\020\003\022\024\n\020ENVIRONMENT_LAND\020\004\022"
    "\025\n\021ENVIRONMENT_SPACE\020\005*\267\030\n\013Nationality\022\027"
    "\n\023NATIONALITY_INVALID\020\000\022\027\n\023NATIONALITY_A"
    "LBANIA\020\001\022\027\n\023NATIONALITY_ALGERIA\020>\022\031\n\025NAT"
    "IONALITY_ARGENTINA\020O\022\027\n\023NATIONALITY_ARME"
    "NIA\020\002\022\031\n\025NATIONALITY_AUSTRALIA\020\003\022\027\n\023NATI"
    "ONALITY_AUSTRIA\020\004\022\032\n\026NATIONALITY_AZERBAI"
    "JAN\020\005\022\027\n\023NATIONALITY_BELARUS\020\006\022\027\n\023NATION"
    "ALITY_BELGIUM\020\007\022\027\n\023NATIONALITY_BOLIVIA\020j"
    "\022&\n\"NATIONALITY_BOSNIA_AND_HERZEGOVINA\020\010"
    "\022\026\n\022NATIONALITY_BRAZIL\020P\022\030\n\024NATIONALITY_"
    "BULGARIA\020\t\022\030\n\024NATIONALITY_CAMBODIA\020D\022\026\n\022"
    "NATIONALITY_CANADA\020\n\022\025\n\021NATIONALITY_CHIL"
    "E\020Q\022\025\n\021NATIONALITY_CHINA\020H\022\030\n\024NATIONALIT"
    "Y_COLOMBIA\020R\022\027\n\023NATIONALITY_CROATIA\020\013\022\024\n"
    "\020NATIONALITY_CUBA\020W\022\026\n\022NATIONALITY_CYPRU"
    "S\0205\022\036\n\032NATIONALITY_CZECH_REPUBLIC\020\014\0224\n0N"
    "ATIONALITY_DEMOCRATIC_PEOPLES_REPUBLIC_O"
    "F_KOREA\020J\022\027\n\023NATIONALITY_DENMARK\020\r\022\"\n\036NA"
    "TIONALITY_DOMINICAN_REPUBLIC\020X\022\027\n\023NATION"
    "ALITY_ECUADOR\020k\022\025\n\021NATIONALITY_EGYPT\0206\022\027"
    "\n\023NATIONALITY_ESTONIA\020\016\022\030\n\024NATIONALITY_E"
    "THIOPIA\020\?\022\027\n\023NATIONALITY_FINLAND\020\017\022\026\n\022NA"
    "TIONALITY_FRANCE\020\020\022\027\n\023NATIONALITY_GEORGI"
    "A\020\021\022\027\n\023NATIONALITY_GERMANY\020\022\022\026\n\022NATIONAL"
    "ITY_GREECE\020\023\022\031\n\025NATIONALITY_GUATEMALA\020l\022"
    "\026\n\022NATIONALITY_GUINEA\020\\\022\027\n\023NATIONALITY_H"
    "UNGARY\020\024\022\027\n\023NATIONALITY_ICELAND\020\025\022\025\n\021NAT"
    "IONALITY_INDIA\020B\022\031\n\025NATIONALITY_INDONESI"
    "A\020g\022\'\n#NATIONALITY_INTERNATIONAL_RED_CRO"
    "SS\020q\022\024\n\020NATIONALITY_IRAQ\0208\022\027\n\023NATIONALIT"
    "Y_IRELAND\020\026\022(\n$NATIONALITY_ISLAMIC_REPUB"
    "LIC_OF_IRAN\0207\022\026\n\022NATIONALITY_ISRAEL\0209\022\025\n"
    "\021NATIONALITY_ITALY\020\027\022\027\n\023NATIONALITY_JAMA"
    "ICA\020p\022\025\n\021NATIONALITY_JAPAN\020L\022\026\n\022NATIONAL"
    "ITY_JORDAN\020:\022\032\n\026NATIONALITY_KAZAKHSTAN\020\030"
    "\022\026\n\022NATIONALITY_KUWAIT\020Z\022 \n\034NATIONALITY_"
    "KYRGHYZ_REPUBLIC\020\031\022/\n+NATIONALITY_LAO_PE"
    "OPLES_DEMOCRATIC_REPUBLIC\020E\022\026\n\022NATIONALI"
    "TY_LATVIA\020\032\022\027\n\023NATIONALITY_LEBANON\020;\022\027\n\023"
    "NATIONALITY_LIBERIA\020@\022\031\n\025NATIONALITY_LIT"
    "HUANIA\020\033\022\032\n\026NATIONALITY_LUXEMBOURG\020\034\022\032\n\026"
    "NATIONALITY_MADAGASCAR\020]\022\030\n\024NATIONALITY_"
    "MALAYSIA\020h\022\025\n\021NATIONALITY_MALTA\020\035\022\026\n\022NAT"
    "IONALITY_MEXICO\020S\022\027\n\023NATIONALITY_MOLDOVA"
    "\020\036\022\032\n\026NATIONALITY_MONTENEGRO\020\037\022\027\n\023NATION"
    "ALITY_MOROCCO\020^\022\027\n\023NATIONALITY_MYANMAR\020f"
    "\022\024\n\020NATIONALITY_NATO\020 \022\033\n\027NATIONALITY_NE"
    "THERLANDS\020!\022\033\n\027NATIONALITY_NEW_ZEALAND\020N"
    "\022\031\n\025NATIONALITY_NICARAGUA\020m\022\027\n\023NATIONALI"
    "TY_NIGERIA\020_\022\026\n\022NATIONALITY_NORWAY\020\"\022\030\n\024"
    "NATIONALITY_PAKISTAN\020C\022\026\n\022NATIONALITY_PA"
    "NAMA\020T\022\030\n\024NATIONALITY_PARAGUAY\020n\022\024\n\020NATI"
    "ONALITY_PERU\020U\022\033\n\027NATIONALITY_PHILIPPINE"
    "S\020M\022\026\n\022NATIONALITY_POLAND\020#\022\030\n\024NATIONALI"
    "TY_PORTUGAL\020$\022!\n\035NATIONALITY_REPUBLIC_OF"
    "_KOREA\020K\022\027\n\023NATIONALITY_ROMANIA\020%\022\026\n\022NAT"
    "IONALITY_RUSSIA\020&\022\034\n\030NATIONALITY_SAUDI_A"
    "RABIA\020<\022\027\n\023NATIONALITY_SENEGAL\020`\022\026\n\022NATI"
    "ONALITY_SERBIA\020\'\022\031\n\025NATIONALITY_SINGAPOR"
    "E\020i\022\030\n\024NATIONALITY_SLOVAKIA\020(\022\030\n\024NATIONA"
    "LITY_SLOVENIA\020)\022\034\n\030NATIONALITY_SOUTH_AFR"
    "ICA\020A\022\025\n\021NATIONALITY_SPAIN\020*\022\025\n\021NATIONAL"
    "ITY_SUDAN\020b\022\026\n\022NATIONALITY_SWEDEN\020+\022\033\n\027N"
    "ATIONALITY_SWITZERLAND\020,\022$\n NATIONALITY_"
    "SYRIAN_ARAB_REPUBLIC\020=\022\026\n\022NATIONALITY_TA"
    "IWAN\020I\022\032\n\026NATIONALITY_TAJIKISTAN\020-\022\030\n\024NA"
    "TIONALITY_THAILAND\020F\0229\n5NATIONALITY_THE_"
    "FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA\020.\022"
    "\027\n\023NATIONALITY_TUNISIA\020d\022\026\n\022NATIONALITY_"
    "TURKEY\020/\022\034\n\030NATIONALITY_TURKMENISTAN\0200\022\026"
    "\n\022NATIONALITY_UGANDA\020e\022\027\n\023NATIONALITY_UK"
    "RAINE\0201\022\036\n\032NATIONALITY_UNITED_KINGDOM\0202\022"
    "\036\n\032NATIONALITY_UNITED_NATIONS\020Y\022+\n\'NATIO"
    "NALITY_UNITED_REPUBLIC_OF_TANZANIA\020c\022(\n$"
    "NATIONALITY_UNITED_STATES_OF_AMERICA\0203\022\027"
    "\n\023NATIONALITY_URUGUAY\020o\022\032\n\026NATIONALITY_U"
    "ZBEKISTAN\0204\022\031\n\025NATIONALITY_VENEZUELA\020V\022\027"
    "\n\023NATIONALITY_VIETNAM\020G\022\025\n\021NATIONALITY_Y"
    "EMEN\020[\022\030\n\024NATIONALITY_ZIMBABWE\020aB\225\001\n\027com"
    ".anduril.ontology.v1B\014TypePubProtoP\001\242\002\003A"
    "OX\252\002\023Anduril.Ontology.V1\312\002\023Anduril\\Ontol"
    "ogy\\V1\342\002\037Anduril\\Ontology\\V1\\GPBMetadata"
    "\352\002\025Anduril::Ontology::V1b\006proto3"
};
static ::absl::once_flag descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto = {
    false,
    false,
    3712,
    descriptor_table_protodef_anduril_2fontology_2fv1_2ftype_2epub_2eproto,
    "anduril/ontology/v1/type.pub.proto",
    &descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_anduril_2fontology_2fv1_2ftype_2epub_2eproto::offsets,
    file_level_enum_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto,
    file_level_service_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto,
};
namespace anduril {
namespace ontology {
namespace v1 {
const ::google::protobuf::EnumDescriptor* Disposition_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto);
  return file_level_enum_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Disposition_internal_data_[] = {
    458752u, 0u, };
bool Disposition_IsValid(int value) {
  return 0 <= value && value <= 6;
}
const ::google::protobuf::EnumDescriptor* Environment_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto);
  return file_level_enum_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Environment_internal_data_[] = {
    393216u, 0u, };
bool Environment_IsValid(int value) {
  return 0 <= value && value <= 5;
}
const ::google::protobuf::EnumDescriptor* Nationality_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto);
  return file_level_enum_descriptors_anduril_2fontology_2fv1_2ftype_2epub_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t Nationality_internal_data_[] = {
    7471104u, 0u, };
bool Nationality_IsValid(int value) {
  return 0 <= value && value <= 113;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ontology
}  // namespace anduril
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
