// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anduril/entitymanager/v1/payloads.pub.proto

#include "anduril/entitymanager/v1/payloads.pub.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace anduril {
namespace entitymanager {
namespace v1 {

inline constexpr PayloadConfiguration::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : effective_environment_{},
        _effective_environment_cached_byte_size_{0},
        capability_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        quantity_{0u},
        payload_operational_state_{static_cast< ::anduril::entitymanager::v1::PayloadOperationalState >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadConfiguration::PayloadConfiguration(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PayloadConfigurationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadConfigurationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadConfigurationDefaultTypeInternal() {}
  union {
    PayloadConfiguration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadConfigurationDefaultTypeInternal _PayloadConfiguration_default_instance_;

inline constexpr Payload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        config_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Payload::Payload(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadDefaultTypeInternal() {}
  union {
    Payload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadDefaultTypeInternal _Payload_default_instance_;

inline constexpr Payloads::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_configurations_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Payloads::Payloads(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PayloadsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadsDefaultTypeInternal() {}
  union {
    Payloads _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadsDefaultTypeInternal _Payloads_default_instance_;
}  // namespace v1
}  // namespace entitymanager
}  // namespace anduril
static ::_pb::Metadata file_level_metadata_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto = nullptr;
const ::uint32_t TableStruct_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Payloads, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Payloads, _impl_.payload_configurations_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Payload, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Payload, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Payload, _impl_.config_),
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _impl_.capability_id_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _impl_.quantity_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _impl_.effective_environment_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _impl_.payload_operational_state_),
    PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::PayloadConfiguration, _impl_.payload_description_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::anduril::entitymanager::v1::Payloads)},
        {9, 18, -1, sizeof(::anduril::entitymanager::v1::Payload)},
        {19, -1, -1, sizeof(::anduril::entitymanager::v1::PayloadConfiguration)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::anduril::entitymanager::v1::_Payloads_default_instance_._instance,
    &::anduril::entitymanager::v1::_Payload_default_instance_._instance,
    &::anduril::entitymanager::v1::_PayloadConfiguration_default_instance_._instance,
};
const char descriptor_table_protodef_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n+anduril/entitymanager/v1/payloads.pub."
    "proto\022\030anduril.entitymanager.v1\032*anduril"
    "/entitymanager/v1/options.pub.proto\032\"and"
    "uril/ontology/v1/type.pub.proto\"i\n\010Paylo"
    "ads\022]\n\026payload_configurations\030\001 \003(\0132!.an"
    "duril.entitymanager.v1.PayloadB\003\310>\001R\025pay"
    "loadConfigurations\"Q\n\007Payload\022F\n\006config\030"
    "\001 \001(\0132..anduril.entitymanager.v1.Payload"
    "ConfigurationR\006config\"\316\002\n\024PayloadConfigu"
    "ration\022#\n\rcapability_id\030\001 \001(\tR\014capabilit"
    "yId\022\032\n\010quantity\030\004 \001(\rR\010quantity\022U\n\025effec"
    "tive_environment\030\005 \003(\0162 .anduril.ontolog"
    "y.v1.EnvironmentR\024effectiveEnvironment\022m"
    "\n\031payload_operational_state\030\006 \001(\01621.andu"
    "ril.entitymanager.v1.PayloadOperationalS"
    "tateR\027payloadOperationalState\022/\n\023payload"
    "_description\030\007 \001(\tR\022payloadDescription*\272"
    "\002\n\027PayloadOperationalState\022%\n!PAYLOAD_OP"
    "ERATIONAL_STATE_INVALID\020\000\022!\n\035PAYLOAD_OPE"
    "RATIONAL_STATE_OFF\020\001\022-\n)PAYLOAD_OPERATIO"
    "NAL_STATE_NON_OPERATIONAL\020\002\022&\n\"PAYLOAD_O"
    "PERATIONAL_STATE_DEGRADED\020\003\022)\n%PAYLOAD_O"
    "PERATIONAL_STATE_OPERATIONAL\020\004\022,\n(PAYLOA"
    "D_OPERATIONAL_STATE_OUT_OF_SERVICE\020\005\022%\n!"
    "PAYLOAD_OPERATIONAL_STATE_UNKNOWN\020\006B\201\002\n\034"
    "com.anduril.entitymanager.v1B\020PayloadsPu"
    "bProtoP\001ZMghe.anduril.dev/anduril/anduri"
    "lapis-go/anduril/entitymanager/v1;entity"
    "manager\242\002\003AEX\252\002\030Anduril.Entitymanager.V1"
    "\312\002\030Anduril\\Entitymanager\\V1\342\002$Anduril\\En"
    "titymanager\\V1\\GPBMetadata\352\002\032Anduril::En"
    "titymanager::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_deps[2] =
    {
        &::descriptor_table_anduril_2fentitymanager_2fv1_2foptions_2epub_2eproto,
        &::descriptor_table_anduril_2fontology_2fv1_2ftype_2epub_2eproto,
};
static ::absl::once_flag descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto = {
    false,
    false,
    1263,
    descriptor_table_protodef_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto,
    "anduril/entitymanager/v1/payloads.pub.proto",
    &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_once,
    descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto::offsets,
    file_level_metadata_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto,
    file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto,
    file_level_service_descriptors_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_getter() {
  return &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto(&descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto);
namespace anduril {
namespace entitymanager {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PayloadOperationalState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto);
  return file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PayloadOperationalState_internal_data_[] = {
    458752u, 0u, };
bool PayloadOperationalState_IsValid(int value) {
  return 0 <= value && value <= 6;
}
// ===================================================================

class Payloads::_Internal {
 public:
};

Payloads::Payloads(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.Payloads)
}
inline PROTOBUF_NDEBUG_INLINE Payloads::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : payload_configurations_{visibility, arena, from.payload_configurations_},
        _cached_size_{0} {}

Payloads::Payloads(
    ::google::protobuf::Arena* arena,
    const Payloads& from)
    : ::google::protobuf::Message(arena) {
  Payloads* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:anduril.entitymanager.v1.Payloads)
}
inline PROTOBUF_NDEBUG_INLINE Payloads::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_configurations_{visibility, arena},
        _cached_size_{0} {}

inline void Payloads::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Payloads::~Payloads() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.Payloads)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Payloads::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Payloads::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.Payloads)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_configurations_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Payloads::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Payloads::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Payloads_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .anduril.entitymanager.v1.Payload payload_configurations = 1 [json_name = "payloadConfigurations", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Payloads, _impl_.payload_configurations_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .anduril.entitymanager.v1.Payload payload_configurations = 1 [json_name = "payloadConfigurations", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(Payloads, _impl_.payload_configurations_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::Payload>()},
  }}, {{
  }},
};

::uint8_t* Payloads::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.Payloads)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .anduril.entitymanager.v1.Payload payload_configurations = 1 [json_name = "payloadConfigurations", (.anduril.entitymanager.v1.overridable) = true];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_payload_configurations_size()); i < n; i++) {
    const auto& repfield = this->_internal_payload_configurations().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.Payloads)
  return target;
}

::size_t Payloads::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.Payloads)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .anduril.entitymanager.v1.Payload payload_configurations = 1 [json_name = "payloadConfigurations", (.anduril.entitymanager.v1.overridable) = true];
  total_size += 1UL * this->_internal_payload_configurations_size();
  for (const auto& msg : this->_internal_payload_configurations()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Payloads::_class_data_ = {
    Payloads::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Payloads::GetClassData() const {
  return &_class_data_;
}

void Payloads::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Payloads*>(&to_msg);
  auto& from = static_cast<const Payloads&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.Payloads)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_payload_configurations()->MergeFrom(
      from._internal_payload_configurations());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Payloads::CopyFrom(const Payloads& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.Payloads)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Payloads::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Payloads::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Payloads::InternalSwap(Payloads* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.payload_configurations_.InternalSwap(&other->_impl_.payload_configurations_);
}

::google::protobuf::Metadata Payloads::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_getter, &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_once,
      file_level_metadata_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[0]);
}
// ===================================================================

class Payload::_Internal {
 public:
  using HasBits = decltype(std::declval<Payload>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Payload, _impl_._has_bits_);
  static const ::anduril::entitymanager::v1::PayloadConfiguration& config(const Payload* msg);
  static void set_has_config(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::anduril::entitymanager::v1::PayloadConfiguration& Payload::_Internal::config(const Payload* msg) {
  return *msg->_impl_.config_;
}
Payload::Payload(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.Payload)
}
inline PROTOBUF_NDEBUG_INLINE Payload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Payload::Payload(
    ::google::protobuf::Arena* arena,
    const Payload& from)
    : ::google::protobuf::Message(arena) {
  Payload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.config_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::anduril::entitymanager::v1::PayloadConfiguration>(arena, *from._impl_.config_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:anduril.entitymanager.v1.Payload)
}
inline PROTOBUF_NDEBUG_INLINE Payload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Payload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.config_ = {};
}
Payload::~Payload() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.Payload)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Payload::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.config_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.Payload)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.config_ != nullptr);
    _impl_.config_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Payload::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Payload::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Payload, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Payload_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .anduril.entitymanager.v1.PayloadConfiguration config = 1 [json_name = "config"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Payload, _impl_.config_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .anduril.entitymanager.v1.PayloadConfiguration config = 1 [json_name = "config"];
    {PROTOBUF_FIELD_OFFSET(Payload, _impl_.config_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::PayloadConfiguration>()},
  }}, {{
  }},
};

::uint8_t* Payload::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.Payload)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .anduril.entitymanager.v1.PayloadConfiguration config = 1 [json_name = "config"];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::config(this),
        _Internal::config(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.Payload)
  return target;
}

::size_t Payload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.Payload)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .anduril.entitymanager.v1.PayloadConfiguration config = 1 [json_name = "config"];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.config_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Payload::_class_data_ = {
    Payload::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Payload::GetClassData() const {
  return &_class_data_;
}

void Payload::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Payload*>(&to_msg);
  auto& from = static_cast<const Payload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.Payload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_config()->::anduril::entitymanager::v1::PayloadConfiguration::MergeFrom(
        from._internal_config());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Payload::CopyFrom(const Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Payload::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Payload::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Payload::InternalSwap(Payload* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.config_, other->_impl_.config_);
}

::google::protobuf::Metadata Payload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_getter, &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_once,
      file_level_metadata_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[1]);
}
// ===================================================================

class PayloadConfiguration::_Internal {
 public:
};

PayloadConfiguration::PayloadConfiguration(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.PayloadConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE PayloadConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : effective_environment_{visibility, arena, from.effective_environment_},
        _effective_environment_cached_byte_size_{0},
        capability_id_(arena, from.capability_id_),
        payload_description_(arena, from.payload_description_),
        _cached_size_{0} {}

PayloadConfiguration::PayloadConfiguration(
    ::google::protobuf::Arena* arena,
    const PayloadConfiguration& from)
    : ::google::protobuf::Message(arena) {
  PayloadConfiguration* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, quantity_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, quantity_),
           offsetof(Impl_, payload_operational_state_) -
               offsetof(Impl_, quantity_) +
               sizeof(Impl_::payload_operational_state_));

  // @@protoc_insertion_point(copy_constructor:anduril.entitymanager.v1.PayloadConfiguration)
}
inline PROTOBUF_NDEBUG_INLINE PayloadConfiguration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : effective_environment_{visibility, arena},
        _effective_environment_cached_byte_size_{0},
        capability_id_(arena),
        payload_description_(arena),
        _cached_size_{0} {}

inline void PayloadConfiguration::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, quantity_),
           0,
           offsetof(Impl_, payload_operational_state_) -
               offsetof(Impl_, quantity_) +
               sizeof(Impl_::payload_operational_state_));
}
PayloadConfiguration::~PayloadConfiguration() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.PayloadConfiguration)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PayloadConfiguration::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.capability_id_.Destroy();
  _impl_.payload_description_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PayloadConfiguration::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.PayloadConfiguration)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.effective_environment_.Clear();
  _impl_.capability_id_.ClearToEmpty();
  _impl_.payload_description_.ClearToEmpty();
  ::memset(&_impl_.quantity_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.payload_operational_state_) -
      reinterpret_cast<char*>(&_impl_.quantity_)) + sizeof(_impl_.payload_operational_state_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PayloadConfiguration::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 86, 2> PayloadConfiguration::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967174,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PayloadConfiguration_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string capability_id = 1 [json_name = "capabilityId"];
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.capability_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 quantity = 4 [json_name = "quantity"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PayloadConfiguration, _impl_.quantity_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.quantity_)}},
    // repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.effective_environment_)}},
    // .anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PayloadConfiguration, _impl_.payload_operational_state_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.payload_operational_state_)}},
    // string payload_description = 7 [json_name = "payloadDescription"];
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.payload_description_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string capability_id = 1 [json_name = "capabilityId"];
    {PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.capability_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 quantity = 4 [json_name = "quantity"];
    {PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.quantity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];
    {PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.effective_environment_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedOpenEnum)},
    // .anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];
    {PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.payload_operational_state_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string payload_description = 7 [json_name = "payloadDescription"];
    {PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.payload_description_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\55\15\0\0\0\23\0\0"
    "anduril.entitymanager.v1.PayloadConfiguration"
    "capability_id"
    "payload_description"
  }},
};

::uint8_t* PayloadConfiguration::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.PayloadConfiguration)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string capability_id = 1 [json_name = "capabilityId"];
  if (!this->_internal_capability_id().empty()) {
    const std::string& _s = this->_internal_capability_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "anduril.entitymanager.v1.PayloadConfiguration.capability_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 quantity = 4 [json_name = "quantity"];
  if (this->_internal_quantity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_quantity(), target);
  }

  // repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];
  {
    std::size_t byte_size = _impl_._effective_environment_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(5, _internal_effective_environment(),
                                       byte_size, target);
    }
  }

  // .anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];
  if (this->_internal_payload_operational_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        6, this->_internal_payload_operational_state(), target);
  }

  // string payload_description = 7 [json_name = "payloadDescription"];
  if (!this->_internal_payload_description().empty()) {
    const std::string& _s = this->_internal_payload_description();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "anduril.entitymanager.v1.PayloadConfiguration.payload_description");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.PayloadConfiguration)
  return target;
}

::size_t PayloadConfiguration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.PayloadConfiguration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .anduril.ontology.v1.Environment effective_environment = 5 [json_name = "effectiveEnvironment"];
  {
    std::size_t data_size = 0;
    auto count = static_cast<std::size_t>(this->_internal_effective_environment_size());

    for (std::size_t i = 0; i < count; ++i) {
      data_size += ::_pbi::WireFormatLite::EnumSize(
          this->_internal_effective_environment().Get(static_cast<int>(i)));
    }
    total_size += data_size;
    if (data_size > 0) {
      total_size += 1;
      total_size += ::_pbi::WireFormatLite::Int32Size(
          static_cast<int32_t>(data_size));
    }
    _impl_._effective_environment_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
  }
  // string capability_id = 1 [json_name = "capabilityId"];
  if (!this->_internal_capability_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_capability_id());
  }

  // string payload_description = 7 [json_name = "payloadDescription"];
  if (!this->_internal_payload_description().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_payload_description());
  }

  // uint32 quantity = 4 [json_name = "quantity"];
  if (this->_internal_quantity() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_quantity());
  }

  // .anduril.entitymanager.v1.PayloadOperationalState payload_operational_state = 6 [json_name = "payloadOperationalState"];
  if (this->_internal_payload_operational_state() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_payload_operational_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PayloadConfiguration::_class_data_ = {
    PayloadConfiguration::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PayloadConfiguration::GetClassData() const {
  return &_class_data_;
}

void PayloadConfiguration::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PayloadConfiguration*>(&to_msg);
  auto& from = static_cast<const PayloadConfiguration&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.PayloadConfiguration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_effective_environment()->MergeFrom(from._internal_effective_environment());
  if (!from._internal_capability_id().empty()) {
    _this->_internal_set_capability_id(from._internal_capability_id());
  }
  if (!from._internal_payload_description().empty()) {
    _this->_internal_set_payload_description(from._internal_payload_description());
  }
  if (from._internal_quantity() != 0) {
    _this->_internal_set_quantity(from._internal_quantity());
  }
  if (from._internal_payload_operational_state() != 0) {
    _this->_internal_set_payload_operational_state(from._internal_payload_operational_state());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadConfiguration::CopyFrom(const PayloadConfiguration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.PayloadConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PayloadConfiguration::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PayloadConfiguration::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PayloadConfiguration::InternalSwap(PayloadConfiguration* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.effective_environment_.InternalSwap(&other->_impl_.effective_environment_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.capability_id_, &other->_impl_.capability_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_description_, &other->_impl_.payload_description_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.payload_operational_state_)
      + sizeof(PayloadConfiguration::_impl_.payload_operational_state_)
      - PROTOBUF_FIELD_OFFSET(PayloadConfiguration, _impl_.quantity_)>(
          reinterpret_cast<char*>(&_impl_.quantity_),
          reinterpret_cast<char*>(&other->_impl_.quantity_));
}

::google::protobuf::Metadata PayloadConfiguration::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_getter, &descriptor_table_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto_once,
      file_level_metadata_anduril_2fentitymanager_2fv1_2fpayloads_2epub_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace entitymanager
}  // namespace anduril
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
