// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: anduril/entitymanager/v1/transponder_codes.pub.proto
// Protobuf C++ Version: 5.29.0

#include "anduril/entitymanager/v1/transponder_codes.pub.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace anduril {
namespace entitymanager {
namespace v1 {

inline constexpr ModeS::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        address_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModeS::ModeS(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ModeSDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModeSDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModeSDefaultTypeInternal() {}
  union {
    ModeS _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModeSDefaultTypeInternal _ModeS_default_instance_;

inline constexpr Mode5::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mode5_interrogation_response_{static_cast< ::anduril::entitymanager::v1::InterrogationResponse >(0)},
        mode5_{0u},
        mode5_platform_id_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Mode5::Mode5(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Mode5DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Mode5DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Mode5DefaultTypeInternal() {}
  union {
    Mode5 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Mode5DefaultTypeInternal _Mode5_default_instance_;

inline constexpr TransponderCodes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mode5_{nullptr},
        mode_s_{nullptr},
        mode1_{0u},
        mode2_{0u},
        mode3_{0u},
        mode4_interrogation_response_{static_cast< ::anduril::entitymanager::v1::InterrogationResponse >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TransponderCodes::TransponderCodes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TransponderCodesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransponderCodesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransponderCodesDefaultTypeInternal() {}
  union {
    TransponderCodes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransponderCodesDefaultTypeInternal _TransponderCodes_default_instance_;
}  // namespace v1
}  // namespace entitymanager
}  // namespace anduril
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto = nullptr;
const ::uint32_t
    TableStruct_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode1_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode2_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode3_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode4_interrogation_response_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode5_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::TransponderCodes, _impl_.mode_s_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Mode5, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Mode5, _impl_.mode5_interrogation_response_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Mode5, _impl_.mode5_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::Mode5, _impl_.mode5_platform_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::ModeS, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::ModeS, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::anduril::entitymanager::v1::ModeS, _impl_.address_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::anduril::entitymanager::v1::TransponderCodes)},
        {20, -1, -1, sizeof(::anduril::entitymanager::v1::Mode5)},
        {31, -1, -1, sizeof(::anduril::entitymanager::v1::ModeS)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::anduril::entitymanager::v1::_TransponderCodes_default_instance_._instance,
    &::anduril::entitymanager::v1::_Mode5_default_instance_._instance,
    &::anduril::entitymanager::v1::_ModeS_default_instance_._instance,
};
const char descriptor_table_protodef_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n4anduril/entitymanager/v1/transponder_c"
    "odes.pub.proto\022\030anduril.entitymanager.v1"
    "\032*anduril/entitymanager/v1/options.pub.p"
    "roto\"\324\002\n\020TransponderCodes\022\031\n\005mode1\030\001 \001(\r"
    "B\003\310>\001R\005mode1\022\031\n\005mode2\030\002 \001(\rB\003\310>\001R\005mode2\022"
    "\031\n\005mode3\030\003 \001(\rB\003\310>\001R\005mode3\022v\n\034mode4_inte"
    "rrogation_response\030\004 \001(\0162/.anduril.entit"
    "ymanager.v1.InterrogationResponseB\003\310>\001R\032"
    "mode4InterrogationResponse\022:\n\005mode5\030\005 \001("
    "\0132\037.anduril.entitymanager.v1.Mode5B\003\310>\001R"
    "\005mode5\022;\n\006mode_s\030\006 \001(\0132\037.anduril.entitym"
    "anager.v1.ModeSB\003\310>\001R\005modeS\"\274\001\n\005Mode5\022q\n"
    "\034mode5_interrogation_response\030\001 \001(\0162/.an"
    "duril.entitymanager.v1.InterrogationResp"
    "onseR\032mode5InterrogationResponse\022\024\n\005mode"
    "5\030\002 \001(\rR\005mode5\022*\n\021mode5_platform_id\030\003 \001("
    "\rR\017mode5PlatformId\"1\n\005ModeS\022\016\n\002id\030\001 \001(\tR"
    "\002id\022\030\n\007address\030\002 \001(\rR\007address*\255\001\n\025Interr"
    "ogationResponse\022\"\n\036INTERROGATION_RESPONS"
    "E_INVALID\020\000\022\"\n\036INTERROGATION_RESPONSE_CO"
    "RRECT\020\001\022$\n INTERROGATION_RESPONSE_INCORR"
    "ECT\020\002\022&\n\"INTERROGATION_RESPONSE_NO_RESPO"
    "NSE\020\003B\272\001\n\034com.anduril.entitymanager.v1B\030"
    "TransponderCodesPubProtoP\001\242\002\003AEX\252\002\030Andur"
    "il.Entitymanager.V1\312\002\030Anduril\\Entitymana"
    "ger\\V1\342\002$Anduril\\Entitymanager\\V1\\GPBMet"
    "adata\352\002\032Anduril::Entitymanager::V1b\006prot"
    "o3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto_deps[1] =
    {
        &::descriptor_table_anduril_2fentitymanager_2fv1_2foptions_2epub_2eproto,
};
static ::absl::once_flag descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto = {
    false,
    false,
    1082,
    descriptor_table_protodef_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
    "anduril/entitymanager/v1/transponder_codes.pub.proto",
    &descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto_once,
    descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto::offsets,
    file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
    file_level_service_descriptors_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
};
namespace anduril {
namespace entitymanager {
namespace v1 {
const ::google::protobuf::EnumDescriptor* InterrogationResponse_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto);
  return file_level_enum_descriptors_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t InterrogationResponse_internal_data_[] = {
    262144u, 0u, };
bool InterrogationResponse_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// ===================================================================

class TransponderCodes::_Internal {
 public:
  using HasBits =
      decltype(std::declval<TransponderCodes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_._has_bits_);
};

TransponderCodes::TransponderCodes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.TransponderCodes)
}
inline PROTOBUF_NDEBUG_INLINE TransponderCodes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::anduril::entitymanager::v1::TransponderCodes& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

TransponderCodes::TransponderCodes(
    ::google::protobuf::Arena* arena,
    const TransponderCodes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TransponderCodes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.mode5_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::anduril::entitymanager::v1::Mode5>(
                              arena, *from._impl_.mode5_)
                        : nullptr;
  _impl_.mode_s_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::anduril::entitymanager::v1::ModeS>(
                              arena, *from._impl_.mode_s_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mode1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, mode1_),
           offsetof(Impl_, mode4_interrogation_response_) -
               offsetof(Impl_, mode1_) +
               sizeof(Impl_::mode4_interrogation_response_));

  // @@protoc_insertion_point(copy_constructor:anduril.entitymanager.v1.TransponderCodes)
}
inline PROTOBUF_NDEBUG_INLINE TransponderCodes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TransponderCodes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mode5_),
           0,
           offsetof(Impl_, mode4_interrogation_response_) -
               offsetof(Impl_, mode5_) +
               sizeof(Impl_::mode4_interrogation_response_));
}
TransponderCodes::~TransponderCodes() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.TransponderCodes)
  SharedDtor(*this);
}
inline void TransponderCodes::SharedDtor(MessageLite& self) {
  TransponderCodes& this_ = static_cast<TransponderCodes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.mode5_;
  delete this_._impl_.mode_s_;
  this_._impl_.~Impl_();
}

inline void* TransponderCodes::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TransponderCodes(arena);
}
constexpr auto TransponderCodes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TransponderCodes),
                                            alignof(TransponderCodes));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TransponderCodes::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TransponderCodes_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TransponderCodes::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TransponderCodes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TransponderCodes::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TransponderCodes>(), &TransponderCodes::ByteSizeLong,
            &TransponderCodes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_._cached_size_),
        false,
    },
    &TransponderCodes::kDescriptorMethods,
    &descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TransponderCodes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 0, 2> TransponderCodes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::TransponderCodes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 mode1 = 1 [json_name = "mode1", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TransponderCodes, _impl_.mode1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode1_)}},
    // uint32 mode2 = 2 [json_name = "mode2", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TransponderCodes, _impl_.mode2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode2_)}},
    // uint32 mode3 = 3 [json_name = "mode3", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TransponderCodes, _impl_.mode3_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode3_)}},
    // .anduril.entitymanager.v1.InterrogationResponse mode4_interrogation_response = 4 [json_name = "mode4InterrogationResponse", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TransponderCodes, _impl_.mode4_interrogation_response_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode4_interrogation_response_)}},
    // .anduril.entitymanager.v1.Mode5 mode5 = 5 [json_name = "mode5", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::FastMtS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode5_)}},
    // .anduril.entitymanager.v1.ModeS mode_s = 6 [json_name = "modeS", (.anduril.entitymanager.v1.overridable) = true];
    {::_pbi::TcParser::FastMtS1,
     {50, 1, 1, PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode_s_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 mode1 = 1 [json_name = "mode1", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode1_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 mode2 = 2 [json_name = "mode2", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode2_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 mode3 = 3 [json_name = "mode3", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode3_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .anduril.entitymanager.v1.InterrogationResponse mode4_interrogation_response = 4 [json_name = "mode4InterrogationResponse", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode4_interrogation_response_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .anduril.entitymanager.v1.Mode5 mode5 = 5 [json_name = "mode5", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode5_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .anduril.entitymanager.v1.ModeS mode_s = 6 [json_name = "modeS", (.anduril.entitymanager.v1.overridable) = true];
    {PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode_s_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::Mode5>()},
    {::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::ModeS>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void TransponderCodes::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.TransponderCodes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.mode5_ != nullptr);
      _impl_.mode5_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.mode_s_ != nullptr);
      _impl_.mode_s_->Clear();
    }
  }
  ::memset(&_impl_.mode1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.mode4_interrogation_response_) -
      reinterpret_cast<char*>(&_impl_.mode1_)) + sizeof(_impl_.mode4_interrogation_response_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TransponderCodes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TransponderCodes& this_ = static_cast<const TransponderCodes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TransponderCodes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TransponderCodes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.TransponderCodes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 mode1 = 1 [json_name = "mode1", (.anduril.entitymanager.v1.overridable) = true];
          if (this_._internal_mode1() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_mode1(), target);
          }

          // uint32 mode2 = 2 [json_name = "mode2", (.anduril.entitymanager.v1.overridable) = true];
          if (this_._internal_mode2() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_mode2(), target);
          }

          // uint32 mode3 = 3 [json_name = "mode3", (.anduril.entitymanager.v1.overridable) = true];
          if (this_._internal_mode3() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_mode3(), target);
          }

          // .anduril.entitymanager.v1.InterrogationResponse mode4_interrogation_response = 4 [json_name = "mode4InterrogationResponse", (.anduril.entitymanager.v1.overridable) = true];
          if (this_._internal_mode4_interrogation_response() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                4, this_._internal_mode4_interrogation_response(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .anduril.entitymanager.v1.Mode5 mode5 = 5 [json_name = "mode5", (.anduril.entitymanager.v1.overridable) = true];
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                5, *this_._impl_.mode5_, this_._impl_.mode5_->GetCachedSize(), target,
                stream);
          }

          // .anduril.entitymanager.v1.ModeS mode_s = 6 [json_name = "modeS", (.anduril.entitymanager.v1.overridable) = true];
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.mode_s_, this_._impl_.mode_s_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.TransponderCodes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TransponderCodes::ByteSizeLong(const MessageLite& base) {
          const TransponderCodes& this_ = static_cast<const TransponderCodes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TransponderCodes::ByteSizeLong() const {
          const TransponderCodes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.TransponderCodes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .anduril.entitymanager.v1.Mode5 mode5 = 5 [json_name = "mode5", (.anduril.entitymanager.v1.overridable) = true];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.mode5_);
            }
            // .anduril.entitymanager.v1.ModeS mode_s = 6 [json_name = "modeS", (.anduril.entitymanager.v1.overridable) = true];
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.mode_s_);
            }
          }
           {
            // uint32 mode1 = 1 [json_name = "mode1", (.anduril.entitymanager.v1.overridable) = true];
            if (this_._internal_mode1() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_mode1());
            }
            // uint32 mode2 = 2 [json_name = "mode2", (.anduril.entitymanager.v1.overridable) = true];
            if (this_._internal_mode2() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_mode2());
            }
            // uint32 mode3 = 3 [json_name = "mode3", (.anduril.entitymanager.v1.overridable) = true];
            if (this_._internal_mode3() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_mode3());
            }
            // .anduril.entitymanager.v1.InterrogationResponse mode4_interrogation_response = 4 [json_name = "mode4InterrogationResponse", (.anduril.entitymanager.v1.overridable) = true];
            if (this_._internal_mode4_interrogation_response() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_mode4_interrogation_response());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TransponderCodes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TransponderCodes*>(&to_msg);
  auto& from = static_cast<const TransponderCodes&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.TransponderCodes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.mode5_ != nullptr);
      if (_this->_impl_.mode5_ == nullptr) {
        _this->_impl_.mode5_ =
            ::google::protobuf::Message::CopyConstruct<::anduril::entitymanager::v1::Mode5>(arena, *from._impl_.mode5_);
      } else {
        _this->_impl_.mode5_->MergeFrom(*from._impl_.mode5_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.mode_s_ != nullptr);
      if (_this->_impl_.mode_s_ == nullptr) {
        _this->_impl_.mode_s_ =
            ::google::protobuf::Message::CopyConstruct<::anduril::entitymanager::v1::ModeS>(arena, *from._impl_.mode_s_);
      } else {
        _this->_impl_.mode_s_->MergeFrom(*from._impl_.mode_s_);
      }
    }
  }
  if (from._internal_mode1() != 0) {
    _this->_impl_.mode1_ = from._impl_.mode1_;
  }
  if (from._internal_mode2() != 0) {
    _this->_impl_.mode2_ = from._impl_.mode2_;
  }
  if (from._internal_mode3() != 0) {
    _this->_impl_.mode3_ = from._impl_.mode3_;
  }
  if (from._internal_mode4_interrogation_response() != 0) {
    _this->_impl_.mode4_interrogation_response_ = from._impl_.mode4_interrogation_response_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TransponderCodes::CopyFrom(const TransponderCodes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.TransponderCodes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TransponderCodes::InternalSwap(TransponderCodes* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode4_interrogation_response_)
      + sizeof(TransponderCodes::_impl_.mode4_interrogation_response_)
      - PROTOBUF_FIELD_OFFSET(TransponderCodes, _impl_.mode5_)>(
          reinterpret_cast<char*>(&_impl_.mode5_),
          reinterpret_cast<char*>(&other->_impl_.mode5_));
}

::google::protobuf::Metadata TransponderCodes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Mode5::_Internal {
 public:
};

Mode5::Mode5(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.Mode5)
}
Mode5::Mode5(
    ::google::protobuf::Arena* arena, const Mode5& from)
    : Mode5(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Mode5::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Mode5::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, mode5_interrogation_response_),
           0,
           offsetof(Impl_, mode5_platform_id_) -
               offsetof(Impl_, mode5_interrogation_response_) +
               sizeof(Impl_::mode5_platform_id_));
}
Mode5::~Mode5() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.Mode5)
  SharedDtor(*this);
}
inline void Mode5::SharedDtor(MessageLite& self) {
  Mode5& this_ = static_cast<Mode5&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Mode5::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Mode5(arena);
}
constexpr auto Mode5::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Mode5),
                                            alignof(Mode5));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Mode5::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Mode5_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Mode5::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Mode5>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Mode5::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Mode5>(), &Mode5::ByteSizeLong,
            &Mode5::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Mode5, _impl_._cached_size_),
        false,
    },
    &Mode5::kDescriptorMethods,
    &descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Mode5::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Mode5::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::Mode5>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .anduril.entitymanager.v1.InterrogationResponse mode5_interrogation_response = 1 [json_name = "mode5InterrogationResponse"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Mode5, _impl_.mode5_interrogation_response_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_interrogation_response_)}},
    // uint32 mode5 = 2 [json_name = "mode5"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Mode5, _impl_.mode5_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_)}},
    // uint32 mode5_platform_id = 3 [json_name = "mode5PlatformId"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Mode5, _impl_.mode5_platform_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_platform_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .anduril.entitymanager.v1.InterrogationResponse mode5_interrogation_response = 1 [json_name = "mode5InterrogationResponse"];
    {PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_interrogation_response_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 mode5 = 2 [json_name = "mode5"];
    {PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 mode5_platform_id = 3 [json_name = "mode5PlatformId"];
    {PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_platform_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Mode5::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.Mode5)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.mode5_interrogation_response_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.mode5_platform_id_) -
      reinterpret_cast<char*>(&_impl_.mode5_interrogation_response_)) + sizeof(_impl_.mode5_platform_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Mode5::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Mode5& this_ = static_cast<const Mode5&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Mode5::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Mode5& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.Mode5)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .anduril.entitymanager.v1.InterrogationResponse mode5_interrogation_response = 1 [json_name = "mode5InterrogationResponse"];
          if (this_._internal_mode5_interrogation_response() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_mode5_interrogation_response(), target);
          }

          // uint32 mode5 = 2 [json_name = "mode5"];
          if (this_._internal_mode5() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_mode5(), target);
          }

          // uint32 mode5_platform_id = 3 [json_name = "mode5PlatformId"];
          if (this_._internal_mode5_platform_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_mode5_platform_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.Mode5)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Mode5::ByteSizeLong(const MessageLite& base) {
          const Mode5& this_ = static_cast<const Mode5&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Mode5::ByteSizeLong() const {
          const Mode5& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.Mode5)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .anduril.entitymanager.v1.InterrogationResponse mode5_interrogation_response = 1 [json_name = "mode5InterrogationResponse"];
            if (this_._internal_mode5_interrogation_response() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_mode5_interrogation_response());
            }
            // uint32 mode5 = 2 [json_name = "mode5"];
            if (this_._internal_mode5() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_mode5());
            }
            // uint32 mode5_platform_id = 3 [json_name = "mode5PlatformId"];
            if (this_._internal_mode5_platform_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_mode5_platform_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Mode5::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Mode5*>(&to_msg);
  auto& from = static_cast<const Mode5&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.Mode5)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_mode5_interrogation_response() != 0) {
    _this->_impl_.mode5_interrogation_response_ = from._impl_.mode5_interrogation_response_;
  }
  if (from._internal_mode5() != 0) {
    _this->_impl_.mode5_ = from._impl_.mode5_;
  }
  if (from._internal_mode5_platform_id() != 0) {
    _this->_impl_.mode5_platform_id_ = from._impl_.mode5_platform_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Mode5::CopyFrom(const Mode5& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.Mode5)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Mode5::InternalSwap(Mode5* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_platform_id_)
      + sizeof(Mode5::_impl_.mode5_platform_id_)
      - PROTOBUF_FIELD_OFFSET(Mode5, _impl_.mode5_interrogation_response_)>(
          reinterpret_cast<char*>(&_impl_.mode5_interrogation_response_),
          reinterpret_cast<char*>(&other->_impl_.mode5_interrogation_response_));
}

::google::protobuf::Metadata Mode5::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModeS::_Internal {
 public:
};

ModeS::ModeS(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:anduril.entitymanager.v1.ModeS)
}
inline PROTOBUF_NDEBUG_INLINE ModeS::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::anduril::entitymanager::v1::ModeS& from_msg)
      : id_(arena, from.id_),
        _cached_size_{0} {}

ModeS::ModeS(
    ::google::protobuf::Arena* arena,
    const ModeS& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ModeS* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.address_ = from._impl_.address_;

  // @@protoc_insertion_point(copy_constructor:anduril.entitymanager.v1.ModeS)
}
inline PROTOBUF_NDEBUG_INLINE ModeS::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        _cached_size_{0} {}

inline void ModeS::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.address_ = {};
}
ModeS::~ModeS() {
  // @@protoc_insertion_point(destructor:anduril.entitymanager.v1.ModeS)
  SharedDtor(*this);
}
inline void ModeS::SharedDtor(MessageLite& self) {
  ModeS& this_ = static_cast<ModeS&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ModeS::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ModeS(arena);
}
constexpr auto ModeS::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ModeS),
                                            alignof(ModeS));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ModeS::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ModeS_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ModeS::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ModeS>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ModeS::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ModeS>(), &ModeS::ByteSizeLong,
            &ModeS::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ModeS, _impl_._cached_size_),
        false,
    },
    &ModeS::kDescriptorMethods,
    &descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ModeS::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> ModeS::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::anduril::entitymanager::v1::ModeS>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 address = 2 [json_name = "address"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModeS, _impl_.address_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ModeS, _impl_.address_)}},
    // string id = 1 [json_name = "id"];
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ModeS, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1 [json_name = "id"];
    {PROTOBUF_FIELD_OFFSET(ModeS, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 address = 2 [json_name = "address"];
    {PROTOBUF_FIELD_OFFSET(ModeS, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\36\2\0\0\0\0\0\0"
    "anduril.entitymanager.v1.ModeS"
    "id"
  }},
};

PROTOBUF_NOINLINE void ModeS::Clear() {
// @@protoc_insertion_point(message_clear_start:anduril.entitymanager.v1.ModeS)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.address_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ModeS::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ModeS& this_ = static_cast<const ModeS&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ModeS::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ModeS& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:anduril.entitymanager.v1.ModeS)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1 [json_name = "id"];
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "anduril.entitymanager.v1.ModeS.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // uint32 address = 2 [json_name = "address"];
          if (this_._internal_address() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_address(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:anduril.entitymanager.v1.ModeS)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ModeS::ByteSizeLong(const MessageLite& base) {
          const ModeS& this_ = static_cast<const ModeS&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ModeS::ByteSizeLong() const {
          const ModeS& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:anduril.entitymanager.v1.ModeS)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string id = 1 [json_name = "id"];
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // uint32 address = 2 [json_name = "address"];
            if (this_._internal_address() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_address());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ModeS::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModeS*>(&to_msg);
  auto& from = static_cast<const ModeS&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:anduril.entitymanager.v1.ModeS)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_address() != 0) {
    _this->_impl_.address_ = from._impl_.address_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModeS::CopyFrom(const ModeS& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:anduril.entitymanager.v1.ModeS)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModeS::InternalSwap(ModeS* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
        swap(_impl_.address_, other->_impl_.address_);
}

::google::protobuf::Metadata ModeS::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace entitymanager
}  // namespace anduril
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_anduril_2fentitymanager_2fv1_2ftransponder_5fcodes_2epub_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
